\subsection{Exception and error handling}\label{refoexcep}
\index{Overview,exceptions}
\index{Exceptions,overview}
:p.
NetRexx doesn't have a \texttt{goto} instruction, but a \texttt{signal}
instruction is provided for abnormal transfer of control, such as when
something unusual occurs.  Using \texttt{signal} raises an
\emph{exception}; all control instructions are then "unwound"
until the exception is caught by a control instruction that specifies a
suitable \texttt{catch} instruction for handling the exception.
:p.
Exceptions are also raised when various errors occur, such as attempting
to divide a number by zero.  For example:
\index{Example,program}
\begin{verbatim}
say 'Please enter a number:'
number=ask
do
  say 'The reciprocal of' number 'is:' 1/number
catch RuntimeException
  say 'Sorry, could not divide "'number'" into 1'
  say 'Please try again.'
end
\end{verbatim}
:p.
Here, the \texttt{catch} instruction will catch any exception that is
raised when the division is attempted (conversion error, divide by zero,
\&), and any instructions that follow it are then executed.  If no
exception is raised, the \texttt{catch} instruction (and any
instructions that follow it) are ignored.
:p.
Any of the control instructions that end with \texttt{end} (\texttt{do},
\texttt{loop}, or \texttt{select}) may be modified with one or more
\texttt{catch} instructions to handle exceptions.
